name: debug

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      php:
        required: true
        type: string
      laravel:
        required: false
        type: string
        default: >-
          [ "x" ]

#MATRIX_JSON: ${{{ format('{"os": {0}, "php": {1}, "laravel": {2}, "testbench": [ "x" ]}', inputs.os, inputs.php, inputs.laravel) }}}
#MATRIX_JSON: '{"os": ${{{ inputs.os }}}, "php": ${{{ inputs.php }}}, "laravel": ${{{ inputs.laravel }}}, "testbench": [ "x" ]}'
#MATRIX_JSON: ${{ format('{{"os": {0}, "php": {1}, "laravel": {2}, "testbench": [ "x" ]}}', inputs.os, inputs.php, inputs.laravel) }}

jobs:
  matrix:
    name: Create Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }} 
    steps:
      - name: Checkout shared workflows repo
        uses: actions/checkout@v3
        with:
            repository: knutle/workflows

      - name: DEBUG
        run: "ls; pwd"

      - name: Generate matrix
        id: set-matrix
        shell: pwsh
        run: "& .github/workflows/create-matrix.ps1 -InputJson '${{ toJson(inputs) }}'"
  
  tests:
    needs: [ matrix ]
    strategy:
      fail-fast: true
      matrix:
        include: ${{ fromJson(needs.matrix.outputs.matrix) }}
    runs-on: ${{ matrix.os }}
    
    #name: P${{ matrix.php }} - L${{ matrix.laravel }}[T${{ matrix.testbench }}] - ${{ matrix.os }}
    #name: P ${{ inputs.php }} - L ${{ inputs.laravel }}[T ${{ matrix.testbench }}] - ${{ inputs.os }}
    #name: P ${{ matrix.php }} - L ${{ matrix.laravel }}[T ${{ matrix.testbench }}] - ${{ matrix.os }} --- P ${{ inputs.php }} - L ${{ inputs.laravel }}[T ${{ matrix.testbench }}] - ${{ inputs.os }}
    name: M ${{ matrix }}

    steps:
      - uses: actions/checkout@v2