name: debug

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      php:
        required: true
        type: string
      laravel:
        required: false
        type: string
        default: "null"

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        os: ${{ fromJson(inputs.os) }}
        php: ${{ fromJson(inputs.php) }}

    name: "O: ${{ matrix.os }}/${{ inputs.os }} - P: ${{ matrix.php }}/${{ inputs.php }} - L: ${{ matrix.laravel }}/${{ inputs.laravel }}"

    steps:
      - uses: actions/checkout@v2