name: debug

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      php:
        required: true
        type: string
      laravel:
        required: false
        type: string
        default: null

jobs:
  matrix:
    name: Create Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }} 
    steps:
      - name: Checkout shared workflows repo
        uses: actions/checkout@v3
        with:
            repository: knutle/workflows

      - name: Generate matrix
        id: set-matrix
        shell: pwsh
        run: "& .github/workflows/create-matrix.ps1 -OS '${{ toJson(inputs.os) }}' -PHP '${{ toJson(inputs.php) }}' -Laravel '${{ toJson(inputs.laravel) }}'"
  
  tests:
    needs: [ matrix ]
    strategy:
      fail-fast: true
      matrix:
        include: ${{ fromJson(needs.matrix.outputs.matrix) }}
    runs-on: ${{ matrix.os }}
    
    name: ${{ matrix.title }}

    steps:
      - uses: actions/checkout@v2