name: debug

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      php:
        required: true
        type: string
      laravel:
        required: false
        type: string
        default: >-
          [ "x" ]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ${{ fromJson(inputs.os) }}
        php: ${{ fromJson(inputs.php) }}
        laravel: ${{ fromJson(inputs.laravel) }}
        include:
          - testbench: ${{ fromJson(inputs.laravel) }}
          - laravel: 8.*
            testbench: ^6.24
          - laravel: 9.*
            testbench: ^7.4

    name: P${{ matrix.php }} - L${{ matrix.laravel || inputs.laravel }}[T${{ matrix.testbench }}] - ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2